/**
 * Restore the per-tool face mapping that was in place before the eight-tool set was installed.
 *
 * Generated by `set_all_tool_faces.mjs` so that "take it back if it looks bad" is one command rather than a
 * reconstruction. It writes only `tool.tools`; every other part of the config is left alone.
 *
 * Usage: `node dsh_orb/restore_tool_faces.mjs`
 */

import { readFileSync, writeFileSync, copyFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'

const CONFIG = join(homedir(), '.dsh', 'dsh-orb', 'memes.json')
const PREVIOUS = {
  "pwsh": "记录 2.gif"
}

const config = JSON.parse(readFileSync(CONFIG, 'utf8'))
copyFileSync(CONFIG, `${CONFIG}.bak-before-restore`)
config.tool = { ...config.tool, enabled: true, tools: PREVIOUS }
writeFileSync(CONFIG, `${JSON.stringify(config, null, 2)}\n`, 'utf8')
console.log(`tool.tools restored to ${JSON.stringify(PREVIOUS)}`)
