/**
 * Set the full per-tool face mapping, and leave behind the one command that puts it back.
 *
 * Eight tools out of the two dozen this machine calls, chosen so each face says something about the action: the
 * packs' own names are the only guide to what a clip looks like, so the mapping is a guess that is cheap to be
 * wrong about — an unlisted tool keeps the shared face, and a listed-but-missing file resolves to nothing.
 *
 * The previous mapping is written next to the config as a restore script rather than only as a `.bak`: the ask
 * was "add them all, and take it back if it looks bad", and a backup file is not that — it is one more thing to
 * reconstruct by hand. The script restores the exact prior mapping and nothing else.
 *
 * Usage: `node dsh_orb/set_all_tool_faces.mjs`
 */

import { readFileSync, writeFileSync, copyFileSync, existsSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'

const PACK = 'C:/Users/digua/Desktop/dsh-orb-cordis/大肥鱼表情包整合/大肥鱼表情包整合'
const CONFIG = join(homedir(), '.dsh', 'dsh-orb', 'memes.json')
const RESTORE = 'C:/Users/digua/Desktop/dsh-orb-cordis/dsh_orb/restore_tool_faces.mjs'

/** The mapping to install, with why each clip was picked — the reasoning is the part that is hard to redo. */
const WANTED = {
  pwsh: '记录 2.gif',
  edit: '打字(普通).gif',
  read: '记录 1.gif',
  grep: '指.gif',
  read_image: '像素墨镜反光.gif',
  todo_write: '有主意了.gif',
  subagent: '扩音器.gif',
  wait: '加载(茶_咖啡杯).gif',
}

const config = JSON.parse(readFileSync(CONFIG, 'utf8'))
const previous = config.tool?.tools ?? {}

for (const [tool, file] of Object.entries(WANTED)) {
  if (!existsSync(join(PACK, file))) {
    console.error(`no such clip: ${file} (for ${tool})`)
    process.exit(1)
  }
}

copyFileSync(CONFIG, `${CONFIG}.bak-before-all-toolfaces`)
config.tool = { ...config.tool, enabled: true, tools: WANTED }
writeFileSync(CONFIG, `${JSON.stringify(config, null, 2)}\n`, 'utf8')

// The undo, as a script that does exactly what this one did in reverse.
writeFileSync(RESTORE, `/**
 * Restore the per-tool face mapping that was in place before the eight-tool set was installed.
 *
 * Generated by \`set_all_tool_faces.mjs\` so that "take it back if it looks bad" is one command rather than a
 * reconstruction. It writes only \`tool.tools\`; every other part of the config is left alone.
 *
 * Usage: \`node dsh_orb/restore_tool_faces.mjs\`
 */

import { readFileSync, writeFileSync, copyFileSync } from 'node:fs'
import { homedir } from 'node:os'
import { join } from 'node:path'

const CONFIG = join(homedir(), '.dsh', 'dsh-orb', 'memes.json')
const PREVIOUS = ${JSON.stringify(previous, null, 2)}

const config = JSON.parse(readFileSync(CONFIG, 'utf8'))
copyFileSync(CONFIG, \`\${CONFIG}.bak-before-restore\`)
config.tool = { ...config.tool, enabled: true, tools: PREVIOUS }
writeFileSync(CONFIG, \`\${JSON.stringify(config, null, 2)}\\n\`, 'utf8')
console.log(\`tool.tools restored to \${JSON.stringify(PREVIOUS)}\`)
`, 'utf8')

console.log(`installed ${Object.keys(WANTED).length} mappings:`)
for (const [tool, file] of Object.entries(WANTED)) console.log(`  ${tool.padEnd(11)} ${file}`)
console.log(`\nprevious mapping (${Object.keys(previous).length}): ${JSON.stringify(previous)}`)
console.log(`undo with:  node dsh_orb/restore_tool_faces.mjs`)
console.log(`backup:     ${CONFIG}.bak-before-all-toolfaces`)
